
# The log file location   
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  # stage: ""
  # prod: ""
databaseAdmin:
  user: ['heggens','myersco']
  
#You have to use the - to keep the order
scheduleDays:
   Monday: 'M'
   Tuesday: 'T'
   Wednesday: 'W'
   Thursday: 'R'
   Friday: 'F'

# For every table in the database, add an item here
models:
  mainDB:
    - User
    - Division
    - Program
    - Subject
    - BannerSchedule
    - BannerCourses
    - Term
    - Course
    - SpecialTopicCourse
    - ProgramChair
    - DivisionChair
    - InstructorCourse
    - InstructorSTCourse
    - Deadline
    - CourseChange
    - InstructorCourseChange
    - Building
    - Rooms
    - ScheduleDays
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/selectTerm"
  - title: "Sequence"
    link: "/selectProgram"
  - title: "Log Out"
    link: "https://login.berea.edu/idp/profile/Logout"

adminMenu:
  - title: "Program Management"
    link:  "/redirect/program_management"
    page: ["programManagement"]
  - title: "Division Management"
    link:  "/redirect/division_management"
    page: ["divisionManagement"]
  - title: "System Management"
    link:  "/admin/systemManagement"
    page: ["systemManagement"]
  - title: "Course Management"
    link:  "/courseManagement/crossListed"
    page: ["tracker","conflicts","crossListed"]
    
specialTopicStates:
  - name: "Incomplete" 
    value: 0
    id: "saved"
    color: "default"
  - name: "Submitted"
    value: 1
    id: "submitted"
    color: "info"
  - name: "Approved"
    value: 2
    id: "approved"
    color: "success"
  - name: "Denied"
    value: 3
    id: "denied"
    color: "danger"
  
specialTopicLogic:
  admin_disabled: [2] #state values where admins can not edit
  submit_form:    [0] #state values where forms can be sumbitted
  approved:       [2] #state values where special topics are approved

termInfo:
#the keys correlate to the last two digits in the term code eg: Fall 2016 = 201611 
    11: 'Fall'                    # e.g. Fall 2016 = 201611
    12: 'Spring'                  # e.g. Spring 2017 = 201612 (note the different year)
    13: '8 Week Summer'       # e.g. 8 Week Summer 2017 = 201613 (note the different year)
    14: '1st 4 Week Summer'
    15: '2nd 4 Week Summer'
    #10: 'Berea Bridge Program'   # e.g. Berea Bridge Program 2016 = 201610    

editForm:
  dataKeys: ['cid','term','section','schedule','room','capacity','crossListed','notes']

specialSchedule:
  # Times that needed to be automatically added on the conflicts.html
  conflicts: ['A1','ZZZ']
  # Times you have to find in the notes section
  unknownTime: ['ZZZ']

changeType:
  create: 'create'
  delete: 'delete'
  update: 'update'

tableLayout:
  order: ['Course Name', 'Taught By', 'Section', 'Schedule', 'Room', 'Capacity', 'Cross Listed', 'Notes', 'Term','Last Edited By']
  Course Name:    0
  Taught By:      1  
  Section:        2
  Schedule:       3
  Room:           4
  Capacity:       5
  Cross Listed:   6
  Notes:          7
  Term:           8
  Last Edited By: 9
  
columnColor:
  edit:     'warning'
  delete:   'danger'
  create:   'success'
  default:  'none'
  verified: 'verified'
  
DEBUG:
  #user: "heggens" #Admin Access
  #user: "pearcej" #Division Chair Access
  #user: "jadudm"  #Program Chair Access
  user: "lovelle" #Professor Access
  
filepath:
  tmp: 'data/tmp'

credits:
  - value: "0.250"
  - value: "0.500"
  - value: "0.750"
  - value: "1.000"
  - value: "2.000"
  
contributors:
  - name: "Cody Myers"
    username: "myersco"
    year: 2017
  - name: "Guillermo Ramos"
    username: "ramosmaciasg"
    year: 2018
  - name: "Sarah Watts"
    username: "wattss"
    year: 2018
  - name: "Jose Zindia"
    username: "zindiaj"
    year: 2018
  - name: "Jonathan Chauwa"
    username: "chauwaj"
    year: 2019
  - name: "Kenny Nelson"
    username: "nelsonk"
    year: 2019
  - name: "Sher Sanginov"
    username: "sanginovs"
    year: 2019
  - name: "Evan Johnson"
    username: "johnsone"
    year: 2019
  - name: "Aleksandra Cvetanovska"
    username: "cvetanovskaa"
    year: 2019
  - name: "Jesson Soto Ventura"
    username: "sotoventuraj"
    year: 2019
    
# The log file location   
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  # stage: ""
  # prod: ""
databaseAdmin:
  user: ['heggens','myersco']


