
# The log file location   
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - User
    - Division
    - Program
    - Subject
    - BannerSchedule
    - BannerCourses
    - Term
    - Course
    - ProgramChair
    - DivisionChair
    - InstructorCourse
    - Deadline
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/redirect/courses"

adminMenu:
  - title: "Program Management"
    link: "/redirect/program_management"
  - title: "Division Management"
    link: "/redirect/division_management"
  - title: "System Management"
    link: "/admin/systemManagement"

DEBUG:
  user: "heggens"