
# The log file location
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  - dev: "data/cas.sql"

  # stage: ""
  # prod: ""
databaseAdmin:
  user: ['heggens','myersco']

db:
  db_name: cas
  host: localhost
  password: 27AM2uzohA@vT2k
  username: casUser
  
  # Correct for display, but does not match DB.
scheduleDays:
  Monday: 'Mon'
  Tuesday: 'Tues'
  Wednesday: 'Wed'
  Thursday: 'Thurs'
  Friday: 'Fri'

scheduleDaysShort:
  Monday: "M"
  Tuesday: "T"
  Wednesday: "W"
  Thursday: "R"
  Friday: "F"

# For every table in the database, add an item here
models:
  mainDB:
    - User
    - Division
    - Program
    - Subject
    - BannerSchedule
    - BannerCourses
    - Term
    - Course
    - CrossListed
    - SpecialTopicCourse
    - ProgramChair
    - DivisionChair
    - BuildingManager
    - InstructorCourse
    - InstructorSTCourse
    - Deadline
    - CourseChange
    - InstructorCourseChange
    - Building
    - Rooms
    - ScheduleDays
    - RoomPreferences
    - TermStates
    - EducationTech

# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/selectTerm"
  - title: "Sequence"
    link: "/selectProgram"
  - title: "Room Preferences"
    link: "/selectTermRP"
  - title: "Rooms"
    link: "/static/classrooms.pdf"
  - title: "Log Out"
    link: "/logout"

# - title: "Building Management"
#     link: "/buildingManagement"

accessLevel:
  - name: "Program Chair"
    id: "program_chair"
  - name: "Division Chair"
    id: "division_chair"
  - name: "Building Manager"
    id: "building_manager"
  - name: "Administrator"
    id: "administrator"

adminMenu:
  # - title: "Program Management" #Not needed after User Management
  #   link:  "/redirect/program_management"
  #   page: ["programManagement"]
  # - title: "Division Management" # we do not need this anymore after adding the user mgmt
  #   link:  "/redirect/division_management"
  #   page: ["divisionManagement"]
  - title: "Term Management" #Change to term management
    link:  "/admin/termManagement"
    page: ["termManagement"]
  - title: "Course Management"
    link:  "/courseManagement/crossListed"
    page: ["tracker","conflicts","crossListed"]
  - title: "User Management"
    link:  "/admin/userManagement" #unsure
    page: ["userManagement"]

  - title: "Room Resolution"
    link:  "/roomResolutionTerm"
    page: ["roomResolution"]



#If you ever change the current states, you cannot duplicate the values, because
#it will mess up what the numbers symbolize inside of the database.
specialTopicStates:
  - name: "Incomplete"
    value: 0
    id: "saved"
    color: "default"
  - name: "Submitted"
    value: 1
    id: "submitted"
    color: "info"
  - name: "Approved"
    value: 2
    id: "approved"
    color: "success"
  - name: "Denied"
    value: 3
    id: "denied"
    color: "danger"

specialTopicLogic:
  admin_disabled: [2] #state values where admins can not edit
  submit_form:    [0] #state values where forms can be sumbitted
  approved:       [2] #state values where special topics are approved
  submitted:      1

termInfo:
#the keys correlate to the last two digits in the term code eg: Fall 2016 = 201611
    11: 'Fall'                    # e.g. Fall 2016 = 201611
    12: 'Spring'                  # e.g. Spring 2017 = 201612 (note the different year)
    13: '8 Week Summer'       # e.g. 8 Week Summer 2017 = 201613 (note the different year)
    14: '1st 4 Week Summer'
    15: '2nd 4 Week Summer'
    #10: 'Berea Bridge Program'   # e.g. Berea Bridge Program 2016 = 201610

editForm:
  dataKeys: ['cid','term','section','schedule','room','capacity','crossListed','notes']

conflicts:
  '91': ['91', '97']
  '92': ['92', '93', '9T', '9U', 'A', 'B', 'G', 'I1', 'M', 'U', 'Y']
  '93': ['92', '93', '94', '9U', '9V', 'A', 'B', 'C', 'G', 'H', 'I1', 'M', 'U', 'Y']
  '94': ['93', '94', '95', '9V', '9W', 'B', 'C', 'H', 'I1', 'M', 'Y']
  '95': ['94', '95', '99', '9W', 'C', 'D', 'H', 'J', 'M', 'Y']
  '96': ['96', '99', '9X', '9Y', 'D', 'E', 'F', 'I', 'J', 'N']
  '97': ['91', '97', '9Z', 'A1', 'K', 'N']
  '98': ['98', 'L']
  '99': ['95', '96', '99', '9X', 'D', 'E', 'H', 'J']
  '9A': ['9A', '9J', 'A', 'G', 'I1', 'M', 'O', 'R', 'U', 'V']
  '9B': ['9B', '9J', '9K', '9Q', 'A', 'B', 'G', 'I1', 'M', 'O', 'R', 'U', 'V', 'X', 'Y', 'Z']
  '9C': ['9C', '9K', '9L', '9Q', 'B', 'C', 'H', 'I1', 'M', 'P', 'R', 'V', 'X', 'Y', 'Z']
  '9D': ['9D', '9L', '9M', '9Q', 'C', 'H', 'M', 'P', 'R', 'V', 'X', 'Y', 'Z']
  '9E': ['9E', '9M', '9R', 'D', 'H', 'J', 'S']
  '9F': ['9F', '9N', '9R', 'D', 'E', 'J', 'Q', 'S']
  '9G': ['9G', '9N', '9O', '9R', 'E', 'F', 'I', 'J', 'N', 'Q', 'S', 'W']
  '9H': ['9H', '9O', '9P', '9S', 'F', 'I', 'N', 'W']
  '9I': ['9I', '9P', '9S', 'A1', 'I', 'K', 'N', 'W']
  '9J': ['9A', '9B', '9J', '9K', '9Q', 'A', 'B', 'G', 'I1', 'M', 'O', 'R', 'U', 'V', 'X', 'Y', 'Z']
  '9K': ['9B', '9C', '9J', '9K', '9L', '9Q', 'A', 'B', 'C', 'G', 'H', 'I1', 'M', 'O', 'P', 'R', 'U', 'V', 'X', 'Y', 'Z']
  '9L': ['9C', '9D', '9K', '9L', '9M', '9Q', 'B', 'C', 'H', 'I1', 'M', 'P', 'R', 'V', 'X', 'Y', 'Z']
  '9M': ['9D', '9E', '9L', '9M', '9Q', '9R', 'C', 'D', 'H', 'J', 'M', 'P', 'R', 'S', 'V', 'X', 'Y', 'Z']
  '9N': ['9F', '9G', '9N', '9O', '9R', 'D', 'E', 'F', 'I', 'J', 'N', 'Q', 'S', 'W']
  '9O': ['9G', '9H', '9N', '9O', '9P', '9R', '9S', 'E', 'F', 'I', 'J', 'N', 'Q', 'S', 'W']
  '9P': ['9H', '9I', '9O', '9P', '9S', 'A1', 'F', 'I', 'K', 'N', 'W']
  '9Q': ['9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', 'A', 'B', 'C', 'G', 'H', 'I1', 'M', 'O', 'P', 'R', 'U', 'V', 'X', 'Y', 'Z']
  '9R': ['9E', '9F', '9G', '9M', '9N', '9O', '9R', 'D', 'E', 'F', 'H', 'I', 'J', 'N', 'Q', 'S', 'W']
  '9S': ['9H', '9I', '9O', '9P', '9S', 'A1', 'F', 'I', 'K', 'N', 'W']
  '9T': ['92', '9T', 'A', 'G', 'I1', 'M', 'U']
  '9U': ['92', '93', '9U', 'A', 'B', 'G', 'I1', 'M', 'U', 'Y']
  '9V': ['93', '94', '9V', 'B', 'C', 'H', 'I1', 'M', 'Y']
  '9W': ['94', '95', '9W', 'C', 'H', 'M', 'Y']
  '9X': ['96', '99', '9X', 'D', 'E', 'J']
  '9Y': ['96', '9Y', 'E', 'F', 'I', 'J', 'N']
  '9Z': ['97', '9Z', 'A1', 'K', 'N']
  'A': ['92', '93', '9A', '9B', '9J', '9K', '9Q', '9T', '9U', 'A', 'G', 'I1', 'M', 'U', 'Y']
  'A1': ['97', '9I', '9P', '9S', '9Z', 'A1', 'I', 'K', 'N', 'W']
  'B': ['92', '93', '94', '9B', '9C', '9J', '9K', '9L', '9Q', '9U', '9V', 'B', 'G', 'I1', 'M', 'U', 'Y']
  'C': ['93', '94', '95', '9C', '9D', '9K', '9L', '9M', '9Q', '9V', '9W', 'C', 'H', 'M', 'Y']
  'D': ['95', '96', '99', '9E', '9F', '9M', '9N', '9R', '9X', 'D', 'H', 'J']
  'E': ['96', '99', '9F', '9G', '9N', '9O', '9R', '9X', '9Y', 'E', 'J']
  'F': ['96', '9G', '9H', '9N', '9O', '9P', '9R', '9S', '9Y', 'F', 'I', 'N', 'W']
  'G': ['92', '93', '9A', '9B', '9J', '9K', '9Q', '9T', '9U', 'A', 'B', 'G', 'I1', 'M', 'U', 'Y']
  'H': ['93', '94', '95', '99', '9C', '9D', '9E', '9K', '9L', '9M', '9Q', '9R', '9V', '9W', 'C', 'D', 'H', 'M', 'Y']
  'I': ['96', '9G', '9H', '9I', '9N', '9O', '9P', '9R', '9S', '9Y', 'A1', 'F', 'I', 'K', 'N', 'W']
  'I1': ['92', '93', '94', '9A', '9B', '9C', '9J', '9K', '9L', '9Q', '9T', '9U', '9V', 'A', 'B', 'G', 'I1', 'M', 'U', 'Y']
  'J': ['95', '96', '99', '9E', '9F', '9G', '9M', '9N', '9O', '9R', '9X', '9Y', 'D', 'E', 'J']
  'K': ['97', '9I', '9P', '9S', '9Z', 'A1', 'I', 'K', 'N']
  'L': ['98', 'L']
  'M': ['92', '93', '94', '95', '9A', '9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', '9T', '9U', '9V', '9W', 'A', 'B', 'C', 'G', 'H', 'I1', 'M', 'U', 'Y']
  'N': ['96', '97', '9G', '9H', '9I', '9N', '9O', '9P', '9R', '9S', '9Y', '9Z', 'A1', 'F', 'I', 'K', 'N']
  'O': ['9A', '9B', '9J', '9K', '9Q', 'O', 'R', 'V', 'X', 'Z']
  'P': ['9C', '9D', '9K', '9L', '9M', '9Q', 'P', 'R', 'V', 'X', 'Z']
  'Q': ['9F', '9G', '9N', '9O', '9R', 'Q', 'S']
  'R': ['9A', '9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', 'O', 'P', 'R', 'V', 'X', 'Z']
  'S': ['9E', '9F', '9G', '9M', '9N', '9O', '9R', 'Q', 'S']
  'T': ['T']
  'U': ['92', '93', '9A', '9B', '9J', '9K', '9Q', '9T', '9U', 'A', 'B', 'G', 'I1', 'M', 'U', 'Y']
  'V': ['9A', '9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', 'O', 'P', 'R', 'V', 'X', 'Z']
  'W': ['9G', '9H', '9I', '9N', '9O', '9P', '9R', '9S', 'A1', 'F', 'I', 'W'] 
  'X': ['9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', 'O', 'P', 'R', 'V', 'X', 'Z']
  'Y': ['92', '93', '94', '95', '9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', '9U', '9V', '9W', 'A', 'B', 'C', 'G', 'H', 'I1', 'M', 'U', 'Y']
  'Z': ['9B', '9C', '9D', '9J', '9K', '9L', '9M', '9Q', 'O', 'P', 'R', 'V', 'X', 'Z']


specialSchedule:
  # Times that needed to be automatically added on the conflicts.html
  conflicts: ['A1','ZZZ']
  # Times you have to find in the notes section
  unknownTime: ['ZZZ']

changeType:
  create: 'create'
  delete: 'delete'
  update: 'update'

tableLayout:
  order: ['Course Name', 'Taught By', 'Section', 'Schedule', 'Room', 'Capacity', 'Cross Listed', 'Notes', 'Term','Last Edited By']
  Course Name:    0
  Taught By:      1
  Section:        2
  Schedule:       3
  Room:           4
  Capacity:       5
  Cross Listed:   6
  Notes:          7
  Term:           8
  Last Edited By: 9

columnColor:
  edit:     'warning'
  delete:   'danger'
  create:   'success'
  default:  'none'
  verified: 'verified'

DEBUG:
  user: "heggens" #Admin Access
  # user: "pearcej" #Division Chair Access
  # user: "nakazawam"  #Program Chair Access
  # user: "lovelle" #Professor Access
  # user: "sldkjfalsdkfj;" #for production
  # user: "stamperfa" #Bldg Mngr Access


filepath:
  tmp: 'data/tmp'

credits:
  - "0.25"
  - "0.5"
  - "0.75"
  - "1.0"
  - "1.25"
  - "1.5"
  - "2.0"

contributors:
  - name: "Cody Myers"
    username: "myersco"
    year: 2017
  - name: "Guillermo Ramos"
    username: "ramosmaciasg"
    year: 2018
  - name: "Sarah Watts"
    username: "wattss"
    year: 2018
  - name: "Jose Zindia"
    username: "zindiaj"
    year: 2018
  - name: "Jonathan Chauwa"
    username: "chauwaj"
    year: 2019
  - name: "Kenny Nelson"
    username: "nelsonk"
    year: 2019
  - name: "Sher Sanginov"
    username: "sanginovs"
    year: 2019
  - name: "Evan Johnson"
    username: "johnsone"
    year: 2019
  - name: "Aleksandra Cvetanovska"
    username: "cvetanovskaa"
    year: 2019
  - name: "Jesson Soto Ventura"
    username: "sotoventuraj"
    year: 2019
  - name: "Jamal Mohamed Aw Yonis"
    username: "awyonis"
    year: "2020"
  - name: "Gerardo Nazar Soto"
    username: "sotog"
    year: "2020"
  - name: "Katelyn Adams"
    username: "adamska"
    year: 2019
  - name: "Anne Otieno"
    username: "otienoa"
    year: 2020
  - name: "Basanta Phuyal"
    username: "phuyalb"
    year: 2020
  - name: "Muhammad Hamza Khattak"
    username: "khattakm"
    year: 2020


# The log file location
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  # stage: ""
  # prod: ""
databaseAdmin:
  user: ['heggens','myersco']

# states
#   0: is the number in the db.
#
states:
  1:
    mainInfo: 'Program and Division Chairs will be able to submit courses to this term.'
    subtext: 'Click the arrow to open course scheduling.'
    btn: 'Open Scheduling'
  2:
    mainInfo: 'Course Scheduling is now open. Program and Division chairs can now submit courses to the term.'
    subtext: 'Click the arrow to lock course scheduling. Chairs will no longer be able to add courses to the term.'
    btn: 'Unlock Scheduling'
  3:
    mainInfo: 'Course Scheduling is now locked. Chairs can no longer submit courses for the term.'
    left_help_text: 'Click the left arrow to unlock course scheduling.'
    right_help_text: 'Click the right arrow to open room selection for faculty.'
    subtext: 'WARNING: Course scheduling will be permanently locked!'
    btn: 'Open Room Preferences'
    download: 'Download Courses'
  4:
    mainInfo: 'Room selection is now open. Faculty can now submit and change their room preferences for their courses.'
    subtext: 'Click the arrow to lock room selection.'
    btn: 'Unlock Room Preferences'
  5:
    mainInfo: 'Room selection is now locked. Faculty can no longer submit or change their preferences.'
    left_help_text: 'Click the left arrow to unlock room selection.'
    right_help_text: 'Click the right arrow to assign rooms.'
    subtext: 'WARNING: Room selection will be permanently locked!'
    btn: 'Assign Rooms'
  6:
    mainInfo: 'Rooms have been assigned.'
    left_help_text: 'Click below to run the room assignment algorithm again.'
    right_help_text: 'Click to Finish term.'
    subtext: 'This indicates that all courses and room assigments are finished'
    btn: 'Reassign Rooms'
    goto_text: 'Click below to go to Room Resolution'
    goto_link: 'Room Resolution'
  7:
    mainInfo: 'The term is complete.'
    mainInfo2: 'Course and room preferences are no longer accepted, and rooms have been assigned.'
    link1:   'Download Courses'
    link2: 'Download Rooms'
    right_help_text: 'Archiving will hide the term from view in other CAS interfaces.'
