
# The log file location   
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - User
    - Division
    - Program
    - Subject
    - BannerSchedule
    - BannerCourses
    - Term
    - Course
    - ProgramChair
    - DivisionChair
    - InstructorCourse
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Program Display"
    link: "/courses"
  - title: "Web Form"
    link: "createPrograms"
  - title: "Relational Table"
    link: "readCourses"

DEBUG:
  user: "heggens"